sudo: required

language: go

services:
  - docker

before_install:
- docker pull hirokiy/go-goa:1.0
- docker-compose up

script:
- go test -v ext/cmd/*.go -f /go/src/github.com/hiromaily/go-goa/resources/tomls/settings.toml
