language: go
sudo: required
go:
  - tip

services:
  - docker

before_install:
  #- docker pull hirokiy/go-goa:1.0
  - docker-compose build
  - docker-compose up -d
  #- go get github.com/tools/godep
  #- go get github.com/mattn/goveralls
  #- go get golang.org/x/tools/cmd/cover

script:
  - docker-compose exec webserver /bin/sh -c "go test -v ext/cmd/*.go -f /go/src/github.com/hiromaily/go-goa/resources/tomls/docker.toml"
  #- go test -v ext/cmd/*.go -f /go/src/github.com/hiromaily/go-goa/resources/tomls/docker.toml

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push hirokiy/go-goa:1.0;

branches:
  only:
    - master
