version: "3.9"

services:
  mysql:
    ports:
      - "${MYSQL_PORT:-13306}:3306"

  webserver:
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./ext:/go/src/github.com/hiromaily/go-goa/ext
      - ./goa:/go/src/github.com/hiromaily/go-goa/goa
      - ./public:/go/src/github.com/hiromaily/go-goa/public
      - ./resources/tomls:/go/src/github.com/hiromaily/go-goa/resources/tomls
      - ./runner.conf:/go/src/github.com/hiromaily/go-goa/runner.conf
    stdin_open: true
    tty: true
    restart: always

    command: ./scripts/wait-mysql.sh 127.0.0.1 13306 realize start
    #command: ["./wait-for-db.sh", "mysql-server", "go-goa", "-f", "/go/src/github.com/hiromaily/go-goa/resources/tomls/docker.toml"]
