version: "3.0"

services:
  mysql:
    ports:
      - "${MYSQL_PORT:-3307}:3306"

  webserver:
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./ext:/go/src/github.com/hiromaily/go-goa/ext
      - ./goa:/go/src/github.com/hiromaily/go-goa/goa
      - ./public:/go/src/github.com/hiromaily/go-goa/public
      - ./resources/tomls:/go/src/github.com/hiromaily/go-goa/resources/tomls
      - ./runner.conf:/go/src/github.com/hiromaily/go-goa/runner.conf
    stdin_open: true
    tty: true
    restart: always
    command: fresh -c /go/src/github.com/hiromaily/go-goa/runner.conf
    #command: fresh
