version: '3.9'

volumes:
  db: {}

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - "./build/docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./build/docker/mysql/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-goa
      MYSQL_USER: guestuser
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'goa-api:v1.0'
    links:
      - mysql:mysql-server
    depends_on:
      - mysql
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    ports:
      - "8090:8090"
    restart: always
    command: -f /workspace/configs/docker.toml

  file-server:
    build:
      context: .
      dockerfile: Dockerfile.file
    image: 'goa-file:v1.0'
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    ports:
      - "8080:8080"
    restart: always
    #command: -f /workspace/configs/docker.toml
