version: '3.0'

volumes:
  db: {}

services:
  mysql:
    image: mysql:5.7
    volumes:
      #- "./docker/mysql/data:/var/lib/mysql"
      - db:/var/lib/mysql
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiromaily
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: 12345678
    ports:
      -  ${MYSQL_PORT:-3307}:3306

  #redis:
  #  image: redis
  #  command: --appendonly yes
  #  volumes:
  #    - "./docker/redis/data:/data"
  #  ports:
  #    - ${REDIS_PORT:-6380}:6379

  #nats:
  #  image: nats

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'hirokiy/go-goa:${IMAGE_TAG:-1.0}'
    links:
      - mysql:mysql-server
      #- redis:redis-server
      #- nats:nats-server
    depends_on:
      - mysql
      #- redis
      #- nats
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    ports:
      - "${API_PORT:-8080}:8080"
    #entrypoint: /go/bin/go-goa
    command: go-goa -f /go/src/github.com/hiromaily/go-goa/resources/tomls/docker.toml