version: '3.2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiromaily
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: 12345678
    ports:
      - 3307:3306
  redis:
    image: redis
    command: --appendonly yes
    volumes:
      - "./docker/redis/data:/data"
  nats:
    image: nats
