version: '3.9'

volumes:
  db: {}

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
      - "./build/docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./build/docker/mysql/init.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-goa
      MYSQL_USER: guestuser
      MYSQL_PASSWORD: secret123
    ports:
      - "3306"

  #redis:
  #  image: redis:6.0.10-alpine3.12
  #  command: --appendonly yes
  #  volumes:
  #    - "./build/docker/redis/data:/data"
  #  ports:
  #    - ${REDIS_PORT:-6380}:6379

  webserver:
    build:
      context: .
      dockerfile: build/Dockerfile
    image: 'hirokiy/go-goa:${IMAGE_TAG:-1.0}'
    links:
      - mysql:mysql-server
      #- redis:redis-server
      #- nats:nats-server
    depends_on:
      - mysql
      #- redis
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    ports:
      - "8080"
    restart: always
    #entrypoint: /go/bin/go-goa
    command: go-goa -f /go/src/github.com/hiromaily/go-goa/configs/docker.toml
