// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	TCompany         string
	TCompanyBranch   string
	TTech            string
	TUser            string
	TUserDislikeTech string
	TUserLikeTech    string
	TUserWorkHistory string
}{
	TCompany:         "t_company",
	TCompanyBranch:   "t_company_branch",
	TTech:            "t_tech",
	TUser:            "t_user",
	TUserDislikeTech: "t_user_dislike_tech",
	TUserLikeTech:    "t_user_like_tech",
	TUserWorkHistory: "t_user_work_history",
}
