// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// TCompanyBranch is an object representing the database table.
type TCompanyBranch struct {
	ID        int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	CompanyID int         `boil:"company_id" json:"company_id" toml:"company_id" yaml:"company_id"`
	IsHQ      null.String `boil:"is_hq" json:"is_hq,omitempty" toml:"is_hq" yaml:"is_hq,omitempty"`
	CountryID int16       `boil:"country_id" json:"country_id" toml:"country_id" yaml:"country_id"`
	Address   null.String `boil:"address" json:"address,omitempty" toml:"address" yaml:"address,omitempty"`
	IsDeleted null.String `boil:"is_deleted" json:"is_deleted,omitempty" toml:"is_deleted" yaml:"is_deleted,omitempty"`
	CreatedAt null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *tCompanyBranchR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tCompanyBranchL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TCompanyBranchColumns = struct {
	ID        string
	CompanyID string
	IsHQ      string
	CountryID string
	Address   string
	IsDeleted string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	CompanyID: "company_id",
	IsHQ:      "is_hq",
	CountryID: "country_id",
	Address:   "address",
	IsDeleted: "is_deleted",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// Generated where

type whereHelperint16 struct{ field string }

func (w whereHelperint16) EQ(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint16) NEQ(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint16) LT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint16) LTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint16) GT(x int16) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint16) GTE(x int16) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint16) IN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint16) NIN(slice []int16) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var TCompanyBranchWhere = struct {
	ID        whereHelperint
	CompanyID whereHelperint
	IsHQ      whereHelpernull_String
	CountryID whereHelperint16
	Address   whereHelpernull_String
	IsDeleted whereHelpernull_String
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperint{field: "`t_company_branch`.`id`"},
	CompanyID: whereHelperint{field: "`t_company_branch`.`company_id`"},
	IsHQ:      whereHelpernull_String{field: "`t_company_branch`.`is_hq`"},
	CountryID: whereHelperint16{field: "`t_company_branch`.`country_id`"},
	Address:   whereHelpernull_String{field: "`t_company_branch`.`address`"},
	IsDeleted: whereHelpernull_String{field: "`t_company_branch`.`is_deleted`"},
	CreatedAt: whereHelpernull_Time{field: "`t_company_branch`.`created_at`"},
	UpdatedAt: whereHelpernull_Time{field: "`t_company_branch`.`updated_at`"},
}

// TCompanyBranchRels is where relationship names are stored.
var TCompanyBranchRels = struct {
}{}

// tCompanyBranchR is where relationships are stored.
type tCompanyBranchR struct {
}

// NewStruct creates a new relationship struct
func (*tCompanyBranchR) NewStruct() *tCompanyBranchR {
	return &tCompanyBranchR{}
}

// tCompanyBranchL is where Load methods for each relationship are stored.
type tCompanyBranchL struct{}

var (
	tCompanyBranchAllColumns            = []string{"id", "company_id", "is_hq", "country_id", "address", "is_deleted", "created_at", "updated_at"}
	tCompanyBranchColumnsWithoutDefault = []string{"company_id", "country_id", "address"}
	tCompanyBranchColumnsWithDefault    = []string{"id", "is_hq", "is_deleted", "created_at", "updated_at"}
	tCompanyBranchPrimaryKeyColumns     = []string{"id"}
)

type (
	// TCompanyBranchSlice is an alias for a slice of pointers to TCompanyBranch.
	// This should generally be used opposed to []TCompanyBranch.
	TCompanyBranchSlice []*TCompanyBranch

	tCompanyBranchQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tCompanyBranchType                 = reflect.TypeOf(&TCompanyBranch{})
	tCompanyBranchMapping              = queries.MakeStructMapping(tCompanyBranchType)
	tCompanyBranchPrimaryKeyMapping, _ = queries.BindMapping(tCompanyBranchType, tCompanyBranchMapping, tCompanyBranchPrimaryKeyColumns)
	tCompanyBranchInsertCacheMut       sync.RWMutex
	tCompanyBranchInsertCache          = make(map[string]insertCache)
	tCompanyBranchUpdateCacheMut       sync.RWMutex
	tCompanyBranchUpdateCache          = make(map[string]updateCache)
	tCompanyBranchUpsertCacheMut       sync.RWMutex
	tCompanyBranchUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single tCompanyBranch record from the query.
func (q tCompanyBranchQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TCompanyBranch, error) {
	o := &TCompanyBranch{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for t_company_branch")
	}

	return o, nil
}

// All returns all TCompanyBranch records from the query.
func (q tCompanyBranchQuery) All(ctx context.Context, exec boil.ContextExecutor) (TCompanyBranchSlice, error) {
	var o []*TCompanyBranch

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TCompanyBranch slice")
	}

	return o, nil
}

// Count returns the count of all TCompanyBranch records in the query.
func (q tCompanyBranchQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count t_company_branch rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tCompanyBranchQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if t_company_branch exists")
	}

	return count > 0, nil
}

// TCompanyBranches retrieves all the records using an executor.
func TCompanyBranches(mods ...qm.QueryMod) tCompanyBranchQuery {
	mods = append(mods, qm.From("`t_company_branch`"))
	return tCompanyBranchQuery{NewQuery(mods...)}
}

// FindTCompanyBranch retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTCompanyBranch(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*TCompanyBranch, error) {
	tCompanyBranchObj := &TCompanyBranch{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `t_company_branch` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, tCompanyBranchObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from t_company_branch")
	}

	return tCompanyBranchObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TCompanyBranch) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no t_company_branch provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(tCompanyBranchColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tCompanyBranchInsertCacheMut.RLock()
	cache, cached := tCompanyBranchInsertCache[key]
	tCompanyBranchInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tCompanyBranchAllColumns,
			tCompanyBranchColumnsWithDefault,
			tCompanyBranchColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tCompanyBranchType, tCompanyBranchMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tCompanyBranchType, tCompanyBranchMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `t_company_branch` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `t_company_branch` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `t_company_branch` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, tCompanyBranchPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into t_company_branch")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tCompanyBranchMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for t_company_branch")
	}

CacheNoHooks:
	if !cached {
		tCompanyBranchInsertCacheMut.Lock()
		tCompanyBranchInsertCache[key] = cache
		tCompanyBranchInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the TCompanyBranch.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TCompanyBranch) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	tCompanyBranchUpdateCacheMut.RLock()
	cache, cached := tCompanyBranchUpdateCache[key]
	tCompanyBranchUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tCompanyBranchAllColumns,
			tCompanyBranchPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update t_company_branch, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `t_company_branch` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, tCompanyBranchPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tCompanyBranchType, tCompanyBranchMapping, append(wl, tCompanyBranchPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update t_company_branch row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for t_company_branch")
	}

	if !cached {
		tCompanyBranchUpdateCacheMut.Lock()
		tCompanyBranchUpdateCache[key] = cache
		tCompanyBranchUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q tCompanyBranchQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for t_company_branch")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for t_company_branch")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TCompanyBranchSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tCompanyBranchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `t_company_branch` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tCompanyBranchPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in tCompanyBranch slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all tCompanyBranch")
	}
	return rowsAff, nil
}

var mySQLTCompanyBranchUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TCompanyBranch) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no t_company_branch provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(tCompanyBranchColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLTCompanyBranchUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tCompanyBranchUpsertCacheMut.RLock()
	cache, cached := tCompanyBranchUpsertCache[key]
	tCompanyBranchUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			tCompanyBranchAllColumns,
			tCompanyBranchColumnsWithDefault,
			tCompanyBranchColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			tCompanyBranchAllColumns,
			tCompanyBranchPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert t_company_branch, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`t_company_branch`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `t_company_branch` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(tCompanyBranchType, tCompanyBranchMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tCompanyBranchType, tCompanyBranchMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for t_company_branch")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == tCompanyBranchMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(tCompanyBranchType, tCompanyBranchMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for t_company_branch")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for t_company_branch")
	}

CacheNoHooks:
	if !cached {
		tCompanyBranchUpsertCacheMut.Lock()
		tCompanyBranchUpsertCache[key] = cache
		tCompanyBranchUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single TCompanyBranch record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TCompanyBranch) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TCompanyBranch provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tCompanyBranchPrimaryKeyMapping)
	sql := "DELETE FROM `t_company_branch` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from t_company_branch")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for t_company_branch")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tCompanyBranchQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no tCompanyBranchQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from t_company_branch")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for t_company_branch")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TCompanyBranchSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tCompanyBranchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `t_company_branch` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tCompanyBranchPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tCompanyBranch slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for t_company_branch")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TCompanyBranch) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTCompanyBranch(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TCompanyBranchSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TCompanyBranchSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tCompanyBranchPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `t_company_branch`.* FROM `t_company_branch` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, tCompanyBranchPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TCompanyBranchSlice")
	}

	*o = slice

	return nil
}

// TCompanyBranchExists checks if the TCompanyBranch row exists.
func TCompanyBranchExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `t_company_branch` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if t_company_branch exists")
	}

	return exists, nil
}
