#local, heroku, docker, staging, production
environment = "docker"

[jwt]
key = "keys"

[mysql]
encrypted = false
host = "mysql-server"
port = 3306
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"
