// Package controllers is based on goa/hy_company.go generated by goagen automatically
package controllers

import (
	"fmt"
	"github.com/goadesign/goa"
	c "github.com/hiromaily/go-goa/ext/context"
	m "github.com/hiromaily/go-goa/ext/models"
	"github.com/hiromaily/go-goa/goa/app"
)

// HyCompanyController implements something.
type HyCompanyController struct {
	*goa.Controller
	ctx *c.Ctx
}

// NewHyCompanyController creates a HyCompany controller.
func NewHyCompanyController(service *goa.Service, ctx *c.Ctx) *HyCompanyController {
	return &HyCompanyController{
		Controller: service.NewController("HyCompanyController"),
		ctx:        ctx,
	}
}

// CompanyList runs the CompanyList action.
func (c *HyCompanyController) CompanyList(ctx *app.CompanyListHyCompanyContext) error {
	fmt.Println("[hy_company][CompanyList]")
	var companies []*app.CompanyIdname

	svc := &m.Company{Db: c.ctx.Db}
	svc.CompanyList(&companies)

	if len(companies) == 0 {
		return ctx.NoContent()
	}

	res := app.CompanyIdnameCollection(companies)
	return ctx.OKIdname(res)
}

// GetCompanyGroup runs the GetCompanyGroup action.
func (c *HyCompanyController) GetCompanyGroup(ctx *app.GetCompanyGroupHyCompanyContext) error {
	fmt.Println("[hy_company][GetCompanyGroup]")
	var companies []*app.Company

	svc := &m.Company{Db: c.ctx.Db}

	err := svc.GetCompanyGroup(ctx.CompanyID, ctx.HqFlg, &companies)
	if err != nil {
		return err
	}

	if len(companies) == 0 {
		return ctx.NoContent()
	}

	res := app.CompanyCollection(companies)
	return ctx.OK(res)
}

// CreateCompany runs the CreateCompany action.
func (c *HyCompanyController) CreateCompany(ctx *app.CreateCompanyHyCompanyContext) error {
	// HyCompanyController_CreateCompany: start_implement

	// Put your logic here

	// HyCompanyController_CreateCompany: end_implement
	res := &app.Company{}
	return ctx.OK(res)
}

// DeleteCompany runs the DeleteCompany action.
func (c *HyCompanyController) DeleteCompany(ctx *app.DeleteCompanyHyCompanyContext) error {
	// HyCompanyController_DeleteCompany: start_implement

	// Put your logic here

	// HyCompanyController_DeleteCompany: end_implement
	return nil
}

// UpdateCompany runs the UpdateCompany action.
func (c *HyCompanyController) UpdateCompany(ctx *app.UpdateCompanyHyCompanyContext) error {
	// HyCompanyController_UpdateCompany: start_implement

	// Put your logic here

	// HyCompanyController_UpdateCompany: end_implement
	res := &app.Company{}
	return ctx.OK(res)
}
