// Package controllers is based on goa/hy_user.go generated by goagen automatically
package controllers

import (
	"fmt"
	"github.com/goadesign/goa"
	c "github.com/hiromaily/go-goa/ext/context"
	m "github.com/hiromaily/go-goa/ext/models"
	"github.com/hiromaily/go-goa/goa/app"
)

// HyUserController implements something.
type HyUserController struct {
	*goa.Controller
	ctx *c.Ctx //Added
}

// NewHyUserController creates a HyUser controller.
func NewHyUserController(service *goa.Service, ctx *c.Ctx) *HyUserController {
	return &HyUserController{
		Controller: service.NewController("HyUserController"),
		ctx:        ctx, //Added
	}
}

// UserList runs the UserList action.
func (c *HyUserController) UserList(ctx *app.UserListHyUserContext) error {
	// HyUserController_UserList: start_implement
	fmt.Println("[hy_user][UserList]", ctx)

	// Get UserList

	//type User struct {
	//	Email     string `form:"email" json:"email" xml:"email"`
	//	FirstName string `form:"first_name" json:"first_name" xml:"first_name"`
	//	LastName  string `form:"last_name" json:"last_name" xml:"last_name"`
	//	// User ID
	//	UserID *int `form:"user_id,omitempty" json:"user_id,omitempty" xml:"user_id,omitempty"`
	//}
	var users []*app.User

	svc := &m.User{Db: c.ctx.Db}
	svc.UserList(&users)

	//if len(users) == 0{
	//}

	//type UserCollection []*User
	res := app.UserCollection(users)
	return ctx.OK(res)
}

// GetUser runs the GetUser action.
func (c *HyUserController) GetUser(ctx *app.GetUserHyUserContext) error {
	// HyUserController_GetUser: start_implement
	fmt.Println("[hy_user][GetUser]", ctx)

	// Put your logic here

	// HyUserController_GetUser: end_implement
	res := &app.User{}
	return ctx.OK(res)
}

// CreateUser runs the CreateUser action.
func (c *HyUserController) CreateUser(ctx *app.CreateUserHyUserContext) error {
	// HyUserController_CreateUser: start_implement

	// Put your logic here

	// HyUserController_CreateUser: end_implement
	res := &app.UserID{}
	return ctx.OKId(res)
}

// DeleteUser runs the DeleteUser action.
func (c *HyUserController) DeleteUser(ctx *app.DeleteUserHyUserContext) error {
	// HyUserController_DeleteUser: start_implement

	// Put your logic here

	// HyUserController_DeleteUser: end_implement
	res := &app.UserID{}
	return ctx.OKId(res)
}

// UpdateUser runs the UpdateUser action.
func (c *HyUserController) UpdateUser(ctx *app.UpdateUserHyUserContext) error {
	// HyUserController_UpdateUser: start_implement
	fmt.Println("[hy_user][UpdateUser]", ctx)

	// Put your logic here

	// HyUserController_UpdateUser: end_implement
	res := &app.UserID{}
	return ctx.OKId(res)
}
