// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "api": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/hiromaily/go-goa/goa/design
// --out=$(GOPATH)/src/github.com/hiromaily/go-goa/goa
// --version=v1.2.0-dirty

package app
