// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "api": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/hiromaily/go-goa/goa/design
// --out=$(GOPATH)/src/github.com/hiromaily/go-goa/goa
// --version=v1.3.1

package test
