#local, heroku, docker, staging, production
environment = "local"

[jwt]
key = "keys"

[mysql]
encrypted = false
host = "localhost"
port = 3307
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"
