#local, heroku, docker, staging, production
environment = "kubernetes"

[jwt]
secret_code = "keys"

[mysql]
encrypted = false
host = "mysql-server"
port = 3306
dbname = "go-goa"
user = "guestuser"
pass = "secret123"
