
[logger]
service = "goa-server"
level = 1 # 0:debug, 1:info, 2:warn, 3:error, 4: fatal, 5: panic, 6: no level, 7: disable
is_stacktrace = true
file_name = "" # e.g. `./goa_api.log`

[jwt]
mode = "hmac" # hmac, rsa
audience = "go-gin.com"
secret_code = "secret1234567890"
private_key = "/set-absolute-path/test/rsakey/jwttest_rsa"
public_key = "/set-absolute-path/test/rsakey/jwttest_rsa.pub"

[hash]
salt = "foo-bar"

[mysql]
encrypted = false
host = "localhost"
port = 3306
dbname = "go-goa"
user = "guestuser"
pass = "secret123"
