#local, heroku, docker, staging, production
environment = "local"

[jwt]
secret_code = "keys"

[mysql]
encrypted = false
host = "localhost"
port = 13306
dbname = "go-goa"
user = "guestuser"
pass = "secret123"
