apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: LoadBalancer
  selector:
    app: mysql
