apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: hirokiy/go-goa:1.0
          name: web
          command: ["/go/bin/go-goa", "-f", "/go/src/github.com/hiromaily/go-goa/resources/tomls/kubernetes.toml"]
          ports:
            - containerPort: 8080
              name: web
