apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: hirokiy/go-goa:1.0
          name: web
          ports:
            - containerPort: 8080
              name: web
          #volumeMounts:
          #  - name: web-storage
          #    mountPath: /go/src/github.com/hiromaily/go-goa
      #volumes:
      #  - name: web-storage
      #    gcePersistentDisk:
      #      pdName: web-disk
      #      fsType: ext4
