name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  demo:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 12
#          cache: npm
#          cache-dependency-path: contracts/quorum/package-lock.json
#      - name: Install Yarn
#        run: |
#          npm install -g yarn
      - name: Build
        run: |
          make build
      - name: Run Docker
        run: |
          docker compose up mysql -d
          sleep 5s
      - name: API Test
        run: |
          make test
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      LINT_VERSION: 'v1.50.1'
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint for resume
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.LINT_VERSION }}
