name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  demo:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Install httpie tool
        run: |
          curl -SsL https://packages.httpie.io/deb/KEY.gpg | apt-key add -
          curl -SsL -o /etc/apt/sources.list.d/httpie.list https://packages.httpie.io/deb/httpie.list
          apt update
          apt install httpie
      - name: Build Docker for go server
        run: |
          make docker-build
      - name: Run Docker
        run: |
          docker compose up -d
          sleep 5s
#  golangci:
#    name: lint
#    runs-on: ubuntu-latest
#    env:
#      LINT_VERSION: 'v1.50.1'
#    steps:
#      - name: Set up Go 1.19
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#      - uses: actions/checkout@v3
#      - name: golangci-lint for resume
#        uses: golangci/golangci-lint-action@v3
#        with:
#          version: ${{ env.LINT_VERSION }}
